### PR TITLE
Make the two panes independently scrollable

### PR DESCRIPTION
**Pull request by Alphare**
This is a small step towards a more ergonomic UI.

### CODE REVIEW

**Comment by xfbs** [comment]
Hey, thanks a lot for working on this!

I tested this out locally and it looks good to me. Putting the styles into a CSS file is definitely a lot cleaner. One thing I saw is that this cuts off the output because the diff view is smaller:

Screenshot from 2023-03-10 21-46-49

Maybe we should make this view take up the remainder of the screen space?

**Comment by Alphare** [comment]
Ah right. I hadn't looked at this specific resolution because the responsiveness should be reworked in the general case. This is something that can be addressed in a separate PR, maybe I'll do it, but I'm working on implementing #7. For now, we could probably just drop the `width` directive. Let me send another version soon-ish.

**Comment by Alphare** [comment]
@xfbs This should fix the specific issue you underlined.

**Comment by xfbs** [comment]
LGTM, thanks for the quick fix!

**Pull request merged**
