### PR TITLE
ignore files created by IntelliJ IDEs

### PR DESCRIPTION
**Pull request by SwishSwushPow**
Ignoring files that are created by IDEs made by IntelliJ (such as RustRover).

### CODE REVIEW

**Comment by xfbs** [comment]
LGTM!

**Comment by xfbs** [comment]
Oops, I noticed that I had messed up the merging of this, because I pushed some code to gitlab to deploy (and it's set up to sync by force-pushing, so it pushed over this). Got the commit in now!

**Comment by SwishSwushPow** [comment]
Ah I see 😅 maybe there is a better way to handle this if more people are contributing in the future? Just to make sure not to lose anything. :)

**Comment by xfbs** [comment]
Yes 😅 it's a bit complicated by the fact that I use GitLab to deploy it, but manage it here. I've changed it to not use force-push, maybe I'll even turn the sync off altogether. It's quite confusing because if I hadn't looked at the commit history I wouldn't have seen that the commit was overwritten. Another possibility would be to deploy it off GitHub pages at some point. Sorry about that! But at least it's fixed now.

**Pull request merged**
