### PR TITLE
Clever context

### PR DESCRIPTION
**Pull request by Alphare**
Just so you're aware, I'm starting this "better context" work, I'm not entirely sure where the UX will land, but I'm making good progress.

### CODE REVIEW

**Comment by Alphare** [comment]
@xfbs pinging you in case draft PRs don't make it to notifications (I don't really use Gitlab... or Git that much for that matter :D)

**Comment by Alphare** [comment]
@xfbs pinging you in case draft PRs don't make it to notifications (I don't really use Gitlab... or Git that much for that matter :D)

**Comment by xfbs** [comment]
Hey, that's awesome! I'm a little under the weather today, so slow to respond. But I'll be happy to merge anything that looks good!

**Comment by xfbs** [comment]
Closing this due to inactivity.

**Pull request closed without merging**
